package com.shellaia.component.spotify;

import com.social100.todero.common.routing.ToolCapabilityManifest;
import com.social100.todero.common.routing.ToolCapabilityProvider;
import com.social100.todero.common.routing.ToolCommandSchema;

import java.util.List;

public final class SpotifyToolCapabilities implements ToolCapabilityProvider {
  @Override
  public ToolCapabilityManifest manifest() {
    return ToolCapabilityManifest.builder()
        .contractVersion(1)
        .componentName("com.shellaia.spotify")
        .toolSummary("Spotify playback, device, queue, search resolution, playlist, and delegated authorization tool.")
        .commands(List.of(
            cmd("events",
                "Manage playback event streaming and optional DJ notifications.",
                List.of("ON|OFF"),
                List.of("intervalMs", "notify-agent=true|false", "notify-min-ms=<ms>", "output=typed|legacy", "filter=all|track|playback|device|context"),
                List.of("events ON", "events OFF 1500 notify-agent=true output=typed filter=track")),
            cmd("html",
                "Render an HTML page representing this component.",
                List.of(),
                List.of(),
                List.of("html")),
            cmd("emit",
                "Emit a demo AIATP event on a selected channel (chat|html|thought).",
                List.of(),
                List.of("channel=chat|html|thought", "message=<text>"),
                List.of("emit?channel=chat&message=hello", "emit?channel=html&message=<b>hello</b>")),
            cmd("auth-status",
                "Inspect delegated Spotify authorization state.",
                List.of(),
                List.of(),
                List.of("auth-status")),
            cmd("auth-begin",
                "Begin delegated Spotify authorization.",
                List.of(),
                List.of("redirect-profile=app|console", "redirect-uri=<uri>", "owner=<binding>"),
                List.of("auth-begin", "auth-begin redirect-profile=console", "auth-begin owner=owner-a")),
            cmd("auth-complete",
                "Complete delegated Spotify authorization.",
                List.of("state=<state>", "code=<code>"),
                List.of("session-id=<id>", "secureEnvelope=<json>"),
                List.of("auth-complete state=<state> code=<code>", "auth-complete session-id=<id> state=<state> code=<code>")),
            cmd("auth-session",
                "Inspect a delegated authorization session.",
                List.of(),
                List.of("session-id=<id>"),
                List.of("auth-session", "auth-session session-id=abc123")),
            cmd("auth-cancel",
                "Cancel a delegated authorization session.",
                List.of(),
                List.of("session-id=<id>"),
                List.of("auth-cancel", "auth-cancel session-id=abc123")),
            cmd("move",
                "Seek within playback.",
                List.of("<position>"),
                List.of(),
                List.of("move 01:23", "move 90")),
            cmd("mute",
                "Mute playback.",
                List.of(),
                List.of(),
                List.of("mute")),
            cmd("pause",
                "Pause playback.",
                List.of(),
                List.of(),
                List.of("pause")),
            cmd("play",
                "Play a track, search query, or context.",
                List.of(),
                List.of("[media]"),
                List.of("play", "play enya caribbean blue")),
            cmd("skip",
                "Skip to the next track.",
                List.of("<+/-seconds>"),
                List.of(),
                List.of("skip 30", "skip -15")),
            cmd("status",
                "Inspect current playback state.",
                List.of(),
                List.of("[all]"),
                List.of("status", "status all")),
            cmd("capabilities",
                "Return the Spotify tool capability manifest for discovery.",
                List.of(),
                List.of(),
                List.of("capabilities")),
            cmd("stop",
                "Stop playback.",
                List.of(),
                List.of(),
                List.of("stop")),
            cmd("volume",
                "Set volume.",
                List.of("<level>"),
                List.of(),
                List.of("volume 75")),
            cmd("volume-down",
                "Decrease volume.",
                List.of(),
                List.of(),
                List.of("volume-down")),
            cmd("volume-up",
                "Increase volume.",
                List.of(),
                List.of(),
                List.of("volume-up")),
            cmd("playlist-remove",
                "Remove current playlist item.",
                List.of(),
                List.of(),
                List.of("playlist-remove")),
            cmd("playlist-next",
                "Advance within the active playlist.",
                List.of(),
                List.of(),
                List.of("playlist-next")),
            cmd("devices",
                "List available devices.",
                List.of(),
                List.of(),
                List.of("devices")),
            cmd("metrics",
                "Inspect playback metrics.",
                List.of(),
                List.of(),
                List.of("metrics")),
            cmd("select-device",
                "Select the active playback device.",
                List.of("<deviceId>"),
                List.of(),
                List.of("select-device device-123")),
            cmd("queue-add",
                "Add an item to the queue.",
                List.of("<spotify:track|episode:uri>"),
                List.of(),
                List.of("queue-add spotify:track:123", "queue-add spotify:episode:456")),
            cmd("queue",
                "Inspect current queue.",
                List.of(),
                List.of(),
                List.of("queue")),
            cmd("previous",
                "Go to previous track.",
                List.of(),
                List.of(),
                List.of("previous")),
            cmd("resolve-track",
                "Resolve a search query to a concrete Spotify track.",
                List.of("<query>"),
                List.of(),
                List.of("resolve-track enya caribbean blue")),
            cmd("recently-played",
                "List recently played tracks.",
                List.of(),
                List.of("[limit<=50]"),
                List.of("recently-played", "recently-played 20")),
            cmd("top-tracks",
                "List top tracks.",
                List.of(),
                List.of("[limit<=50]", "[short_term|medium_term|long_term]"),
                List.of("top-tracks", "top-tracks 10 medium_term")),
            cmd("top-artists",
                "List top artists.",
                List.of(),
                List.of("[limit<=50]", "[short_term|medium_term|long_term]"),
                List.of("top-artists", "top-artists 10 short_term")),
            cmd("shuffle",
                "Control shuffle mode.",
                List.of("<on|off>"),
                List.of(),
                List.of("shuffle on", "shuffle off")),
            cmd("repeat",
                "Control repeat mode.",
                List.of("<off|track|context>"),
                List.of(),
                List.of("repeat off", "repeat track")),
            cmd("like",
                "Save the current track.",
                List.of(),
                List.of(),
                List.of("like")),
            cmd("playlists",
                "List playlists.",
                List.of(),
                List.of("[limit<=50]", "[offset>=0]"),
                List.of("playlists", "playlists 20 0")),
            cmd("playlist-list",
                "List tracks in a playlist.",
                List.of("<playlistId>"),
                List.of("[limit]"),
                List.of("playlist-list abc123", "playlist-list abc123 20")),
            cmd("playlist-add",
                "Add tracks to a playlist.",
                List.of("<playlistId>", "<trackUri>"),
                List.of("[trackUri ...]"),
                List.of("playlist-add abc123 spotify:track:1", "playlist-add abc123 spotify:track:1 spotify:track:2")),
            cmd("playlist-add-current",
                "Add current track to a playlist.",
                List.of("<songTitle>"),
                List.of(),
                List.of("playlist-add-current caribbean blue")),
            cmd("playlist-create",
                "Create a playlist.",
                List.of("<name>"),
                List.of("[public=true|false]", "[description=<text>]"),
                List.of("playlist-create Road Trip", "playlist-create Road Trip public=true description=Driving")),
            cmd("playlist-reorder",
                "Reorder playlist tracks.",
                List.of("<playlistId>", "<rangeStart>", "<insertBefore>"),
                List.of("[rangeLength<=100]"),
                List.of("playlist-reorder abc123 0 5", "playlist-reorder abc123 0 5 3")),
            cmd("playlist-remove-pos",
                "Remove playlist track by position.",
                List.of("<playlistId>", "<position>"),
                List.of(),
                List.of("playlist-remove-pos abc123 2")),
            cmd("playlist-play",
                "Play a playlist.",
                List.of("<playlistId|spotify:playlist:uri>"),
                List.of("[offset]"),
                List.of("playlist-play abc123", "playlist-play spotify:playlist:abc123 3")),
            cmd("play-context",
                "Play a context URI.",
                List.of("<spotify:album|artist|playlist:uri>"),
                List.of("[offset]"),
                List.of("play-context spotify:playlist:abc123", "play-context spotify:album:abc123 2"))
        ))
        .build();
  }

  private static ToolCommandSchema cmd(String name,
                                       String description,
                                       List<String> requiredArgs,
                                       List<String> optionalArgs,
                                       List<String> examples) {
    return ToolCommandSchema.builder()
        .name(name)
        .description(description)
        .requiredArgs(requiredArgs == null ? List.of() : requiredArgs)
        .optionalArgs(optionalArgs == null ? List.of() : optionalArgs)
        .examples(examples == null ? List.of() : examples)
        .build();
  }
}
