package com.shellaia.tutil.todo;

public enum TodoEventType {
  GOAL_CREATED,
  GOAL_UPDATED,
  PHASE_INSERTED,
  PHASE_REORDERED,
  PHASE_DELETED,
  PHASE_UPDATED,
  TASK_INSERTED,
  TASK_REORDERED,
  TASK_DELETED,
  TASK_UPDATED,
  TASK_STATUS_BATCH_UPDATED,
  TASK_CLAIMED,
  TASK_CLAIM_RENEWED,
  TASK_CLAIM_RELEASED
}
