# component.properties (placed at the root of the JAR)
#
# Unique name used by ComponentContext
name=com.shellaia.verbatim.component.vlc
# Optional: your component's own version
version=1.0.0
# Optional: the version of the Component API you were compiled against
componentApiVersion=1.0

